[package]
name = "canvas"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = "1.0.4"
pollster = "0.4.0"
wgpu = { version = "28.0.0" }
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.106"
wasm-bindgen-futures = "0.4.56"
bytemuck = { version = "1.24.0", features = [ "derive" ] }
thiserror = "2.0.17"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
figment = { version = "0.10.19", features = ["env", "toml"] }
serde = { version = "1.0.228", features = ["derive"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.56"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = "1.0.0"
web-sys = { version = "0.3.83", features = [
    'Document',
    'Window',
    'Element',
    'HtmlCanvasElement',
  ]}

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

